### ISSUE TITLE
[BUG] Cannot run SQL queries on Postgres

### ISSUE THREAD

**Issue by chriscorvid** [cweijan/vscode-database-client#178]
- OS INFO : macOS Big Sur v11.2
- VSCODE-DATABASE-CLIENT : v3.6.9

Attempting to run a SQL query on a Postgres DB (v11.5) returns `暂无数据` even if the table has data.

Reverting to the previous version (v3.6.8) restores expected functionality.

Dev Tools shows a stack trace of:

> [Extension Host] stack trace: Error: Not support empty sql!
	at PostgreSqlPageService.build (/git/.vscode/extensions/cweijan.vscode-mysql-client2-3.6.9/out/extension.js:11269:19)	at Function.<anonymous> (/git/.vscode/extensions/cweijan.vscode-mysql-client2-3.6.9/out/extension.js:15862:101)	at Generator.next (<anonymous>)
	at /git/.vscode/extensions/cweijan.vscode-mysql-client2-3.6.9/out/extension.js:15810:71	at new Promise (<anonymous>)
	at module.exports.__awaiter (/git/.vscode/extensions/cweijan.vscode-mysql-client2-3.6.9/out/extension.js:15806:12)	at EventEmitter.<anonymous> (/git/.vscode/extensions/cweijan.vscode-mysql-client2-3.6.9/out/extension.js:15861:69)	at EventEmitter.emit (events.js:315:20)
	at /git/.vscode/extensions/cweijan.vscode-mysql-client2-3.6.9/out/extension.js:3813:48	at _.fire (/git/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1836)	at E.$onMessage (/git/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:54146)	at u._doInvokeHandler (/git/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:12794)	at u._invokeHandler (/git/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:12478)	at u._receiveRequest (/git/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:11145)	at u._receiveOneMessage (/git/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:9931)	at /git/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:8032	at _.fire (/git/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1836)	at E.fire (/git/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15496)	at /git/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:105:29750	at _.fire (/git/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1836)	at E.fire (/git/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15496)	at t._receiveMessage (/git/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:20754)	at /git/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:17640	at _.fire (/git/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1836)	at acceptChunk (/git/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:12861)	at /git/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:12209	at Socket.w (/git/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:105:13173)	at Socket.emit (events.js:315:20)	at addChunk (_stream_readable.js:295:12)	at readableAddChunk (_stream_readable.js:271:9)
	at Socket.Readable.push (_stream_readable.js:212:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)

**Comment by cweijan** [comment]
Thanks, fix at 3.6.10.

**Comment by chriscorvid** [comment]
Tested and works as expected now. Thanks!
