### ISSUE TITLE
Generating mock data failed on Mac[BUG]

### ISSUE THREAD

**Issue by ZNosX** [cweijan/vscode-database-client#238]
- OS INFO :
Mac OS Big Sur

When trying to generate mock data, nothing happens and found this in log:
`[2021-07-03 19:47:23.377] [renderer2] [error] i.mock is not a function: TypeError: i.mock is not a function
    at h.<anonymous> (/Users/Shawn_Qin/.vscode/extensions/cweijan.vscode-mysql-client2-3.9.3/out/extension.js:3:328854)
    at Generator.next (<anonymous>)
    at s (/Users/Shawn_Qin/.vscode/extensions/cweijan.vscode-mysql-client2-3.9.3/out/extension.js:3:327187)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)`

Need some help on what could be the issue here, thanks!

**Comment by cweijan** [comment]
Fix at version 3.9.4.
