### ISSUE TITLE
[BUG] The extension always tries to connect to a db when VSCODE is opened

### ISSUE THREAD

**Issue by elieobeid7** [cweijan/vscode-database-client#51]
- OS INFO : Windos 10, latest version, vscode latest version, vscode-mysql latest version

The MySQL I connect to is behind a VPN. This plugin always tries to connect to MySQL even if I don't want to. If I open vscode to edit some file without being connected to the VPN, the plugin won't be able to connect to the database and it would give this error

```
2020-08-12 09:59:04 : Error: connect ETIMEDOUT
	at Connection.module.exports.Connection._handleConnectTimeout (c:\Users\user-pc\.vscode\extensions\cweijan.vscode-mysql-client2-2.4.6\out\extension.js:5524:13)
	at Object.onceWrapper (events.js:291:20)
	at Socket.emit (events.js:203:13)
	at Socket._onTimeout (net.js:434:8)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)
    --------------------
	at Protocol.module.exports.Protocol._enqueue (c:\Users\user-pc\.vscode\extensions\cweijan.vscode-mysql-client2-2.4.6\out\extension.js:52105:48)
	at Protocol.handshake (c:\Users\user-pc\.vscode\extensions\cweijan.vscode-mysql-client2-2.4.6\out\extension.js:52012:23)
	at Connection.connect (c:\Users\user-pc\.vscode\extensions\cweijan.vscode-mysql-client2-2.4.6\out\extension.js:5231:18)
	at Function.<anonymous> (c:\Users\user-pc\.vscode\extensions\cweijan.vscode-mysql-client2-2.4.6\out\extension.js:300:51)
	at Generator.next (<anonymous>)
	at c:\Users\user-pc\.vscode\extensions\cweijan.vscode-mysql-client2-2.4.6\out\extension.js:216:71
	at new Promise (<anonymous>)
	at module.exports.__awaiter (c:\Users\user-pc\.vscode\extensions\cweijan.vscode-mysql-client2-2.4.6\out\extension.js:212:12)
	at c:\Users\user-pc\.vscode\extensions\cweijan.vscode-mysql-client2-2.4.6\out\extension.js:261:49
	at new Promise (<anonymous>)
	at Function.getConnection (c:\Users\user-pc\.vscode\extensions\cweijan.vscode-mysql-client2-2.4.6\out\extension.js:261:16)
	at ConnectionNode.<anonymous> (c:\Users\user-pc\.vscode\extensions\cweijan.vscode-mysql-client2-2.4.6\out\extension.js:9925:74)
	at Generator.next (<anonymous>)
	at c:\Users\user-pc\.vscode\extensions\cweijan.vscode-mysql-client2-2.4.6\out\extension.js:9885:71
	at new Promise (<anonymous>)
	at module.exports.__awaiter (c:\Users\user-pc\.vscode\extensions\cweijan.vscode-mysql-client2-2.4.6\out\extension.js:9881:12)
	at ConnectionNode.getChildren (c:\Users\user-pc\.vscode\extensions\cweijan.vscode-mysql-client2-2.4.6\out\extension.js:9922:16)
	at DbTreeDataProvider.<anonymous> (c:\Users\user-pc\.vscode\extensions\cweijan.vscode-mysql-client2-2.4.6\out\extension.js:1887:43)
	at Generator.next (<anonymous>)
	at c:\Users\user-pc\.vscode\extensions\cweijan.vscode-mysql-client2-2.4.6\out\extension.js:1861:71
	at new Promise (<anonymous>)
	at module.exports.__awaiter (c:\Users\user-pc\.vscode\extensions\cweijan.vscode-mysql-client2-2.4.6\out\extension.js:1857:12)
	at c:\Users\user-pc\.vscode\extensions\cweijan.vscode-mysql-client2-2.4.6\out\extension.js:1886:79
	at Array.forEach (<anonymous>)
	at DbTreeDataProvider.<anonymous> (c:\Users\user-pc\.vscode\extensions\cweijan.vscode-mysql-client2-2.4.6\out\extension.js:1886:51)
	at Generator.next (<anonymous>)
	at fulfilled (c:\Users\user-pc\.vscode\extensions\cweijan.vscode-mysql-client2-2.4.6\out\extension.js:1858:58)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
connect ETIMEDOUT
-----------------------------------------------------------------------------------------

```

The extension should only try to connect o a db when I click on it and ask it to connect.

**Comment by cweijan** [comment]
This is the expected behavior, You can avoid it by turn below setting off and fold database node when you want to leave.
![image](https://user-images.githubusercontent.com/27798227/89989721-e9eb7380-dcb3-11ea-8aa1-40d1fbc9d016.png)
![image](https://user-images.githubusercontent.com/27798227/89989849-17d0b800-dcb4-11ea-884b-1873a4ef1103.png)

**Comment by cweijan** [comment]
Since version 3.3.0, has been support close connection.
