### ISSUE TITLE
[BUG] / vscode-database-client does not work in code-server. 

### ISSUE THREAD

**Issue by 779505388** [cweijan/vscode-database-client#585]
- OS: Docker(linuxserver/code-server---Ubuntu 20.04.4 LTS aarch64 )

The  vscode-database-client is installed successfully, but it does not work

Run screenshot after installation：
![截屏2022-05-17下午11.01.13.png](https://image.gynl.xyz/2022/05/17/056306bd96771.png)

error   log：
`[2022-05-17 22:50:22.533] [window] [info] Ignoring configured affinity for 'pub.name' because the extension is unknown or cannot execute.
[2022-05-17 22:50:25.070] [window] [error] [Extension Host] (node:8053) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[2022-05-17 22:50:29.132] [window] [error] Can't compute sha-256: Error: Can't compute sha-256
    at t (http://192.168.1.6:8443/static/out/vs/workbench/workbench.web.main.js:798:15149)
    at new F (http://192.168.1.6:8443/static/out/vs/workbench/workbench.web.main.js:1351:9435)
    at v._createInstance (http://192.168.1.6:8443/static/out/vs/workbench/workbench.web.main.js:607:1332)
    at v.createInstance (http://192.168.1.6:8443/static/out/vs/workbench/workbench.web.main.js:607:773)
    at I.createWebviewElement (http://192.168.1.6:8443/static/out/vs/workbench/workbench.web.main.js:1351:21856)
    at D.show (http://192.168.1.6:8443/static/out/vs/workbench/workbench.web.main.js:1291:41076)
    at D.claim (http://192.168.1.6:8443/static/out/vs/workbench/workbench.web.main.js:1291:39597)
    at zo.claimWebview (http://192.168.1.6:8443/static/out/vs/workbench/workbench.web.main.js:1755:82968)
    at zo.setInput (http://192.168.1.6:8443/static/out/vs/workbench/workbench.web.main.js:1755:82879)
    at async i.doSetInput (http://192.168.1.6:8443/static/out/vs/workbench/workbench.web.main.js:2656:26940)
[2022-05-17 22:52:21.719] [window] [error] Can't compute sha-256: Error: Can't compute sha-256
    at t (http://192.168.1.6:8443/static/out/vs/workbench/workbench.web.main.js:798:15149)
    at new F (http://192.168.1.6:8443/static/out/vs/workbench/workbench.web.main.js:1351:9435)
    at v._createInstance (http://192.168.1.6:8443/static/out/vs/workbench/workbench.web.main.js:607:1332)
    at v.createInstance (http://192.168.1.6:8443/static/out/vs/workbench/workbench.web.main.js:607:773)
    at I.createWebviewElement (http://192.168.1.6:8443/static/out/vs/workbench/workbench.web.main.js:1351:21856)
    at D.show (http://192.168.1.6:8443/static/out/vs/workbench/workbench.web.main.js:1291:41076)
    at D.claim (http://192.168.1.6:8443/static/out/vs/workbench/workbench.web.main.js:1291:39597)
    at m.updateTreeVisibility (http://192.168.1.6:8443/static/out/vs/workbench/workbench.web.main.js:2123:34375)
    at http://192.168.1.6:8443/static/out/vs/workbench/workbench.web.main.js:2123:33502
    at S.invoke (http://192.168.1.6:8443/static/out/vs/workbench/workbench.web.main.js:67:145)`

**Comment by cweijan** [comment]
I tried installing a code-server, but the extension works fine.
Consider pressing f12 in the browser, show me the error log.

**Comment by zgangguoguo** [comment]
F12 log:

`VM422:1 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' 'sha256-HuyBNEnumn/Bw3njx2R0EXAv9HicWHLQQd9NJ9ruyrk=' 'sha256-tANAW9Bd3+GA2+NoZNIhDZgoM7p8337ALjYfZSvvZ2M=' 'sha256-yxwQ9j8YGPsfU554CNGiSCW08z5yqDVvuQmssjoPsm8=' 'sha256-fh3TwPMflhsEIpR8g1OYTIMVWhXTLcjQ9kh2tIpmv54=' http://remote". Either the 'unsafe-inline' keyword, a hash ('sha256-rwMOiOeVICH7/Cjy5SkreID3OOi5HTrit357k22hUDQ='), or a nonce ('nonce-...') is required to enable inline execution.`

`console.ts:137 
[Extension Host] (node:12132) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `node --trace-deprecation ...` to show where the warning was created)
D @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:473
_invokeHandler @ rpcProtocol.ts:458
_receiveRequest @ rpcProtocol.ts:374
_receiveOneMessage @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:569
fire @ event.ts:736
fire @ ipc.net.ts:638
_receiveMessage @ ipc.net.ts:958
(anonymous) @ ipc.net.ts:831
invoke @ event.ts:569
fire @ event.ts:736
acceptChunk @ ipc.net.ts:382
(anonymous) @ ipc.net.ts:338
(anonymous) @ browserSocketFactory.ts:230
invoke @ event.ts:569
fire @ event.ts:736
E._fileReader.onload @ browserSocketFactory.ts:91
load (async)
E @ browserSocketFactory.ts:86
create @ browserSocketFactory.ts:203
connect @ browserSocketFactory.ts:277
r @ remoteAgentConnection.ts:193
d @ remoteAgentConnection.ts:234
o @ remoteAgentConnection.ts:321
u @ remoteAgentConnection.ts:363
C @ remoteAgentConnection.ts:433
async function (async)
C @ remoteAgentConnection.ts:432
(anonymous) @ remoteExtensionHost.ts:130
Promise.then (async)
start @ remoteExtensionHost.ts:106
Pr @ extensionHostManager.ts:132
_createInstance @ instantiationService.ts:110
createInstance @ instantiationService.ts:76
n @ extensionHostManager.ts:63
_createExtensionHostManager @ abstractExtensionService.ts:863
_startExtensionHostsIfNecessary @ abstractExtensionService.ts:849
_initialize @ abstractExtensionService.ts:743
(anonymous) @ extensionService.ts:79
async function (async)
(anonymous) @ extensionService.ts:78
Promise.then (async)
Ml @ extensionService.ts:77
_createInstance @ instantiationService.ts:110
_createServiceInstance @ instantiationService.ts:230
_createServiceInstanceWithOwner @ instantiationService.ts:219
_createAndCacheServiceInstance @ instantiationService.ts:208
_safeCreateAndCacheServiceInstance @ instantiationService.ts:151
_getOrCreateServiceInstance @ instantiationService.ts:135
_createInstance @ instantiationService.ts:88
createInstance @ instantiationService.ts:76
acquireInstantiationService @ configurationService.ts:461
(anonymous) @ workbench.ts:214
invokeFunction @ instantiationService.ts:61
initServices @ workbench.ts:208
startup @ workbench.ts:139
open @ web.main.ts:105
async function (async)
open @ web.main.ts:96
a @ web.factory.ts:61
(anonymous) @ workbench.ts:500
(anonymous) @ workbench.ts:507
i._invokeFactory @ loader.js:1185
i.complete @ loader.js:1195
i._onModuleComplete @ loader.js:1821
i._onModuleComplete @ loader.js:1833
i._onModuleComplete @ loader.js:1833
i._onModuleComplete @ loader.js:1833
i._onModuleComplete @ loader.js:1833
i._onModuleComplete @ loader.js:1833
i._onModuleComplete @ loader.js:1833
i._resolve @ loader.js:1781
i.defineModule @ loader.js:1424
o @ loader.js:1709
_ @ loader.js:2208
(anonymous) @ loader.js:2217
(anonymous) @ ?ew=true:59
Promise.then (async)
nlsConfig.loadBundle @ ?ew=true:57
i.load @ loader.js:2211
i._loadPluginDependency @ loader.js:1714
i._resolve @ loader.js:1764
i.defineModule @ loader.js:1424
v @ loader.js:1871
(anonymous) @ fake:1
(anonymous) @ fake:1
log.ts:313   ERR Can't compute sha-256: Error: Can't compute sha-256
    at t (http://192.168.1.6:8443/static/out/vs/workbench/workbench.web.main.js:798:15149)
    at new F (http://192.168.1.6:8443/static/out/vs/workbench/workbench.web.main.js:1351:9435)
    at v._createInstance (http://192.168.1.6:8443/static/out/vs/workbench/workbench.web.main.js:607:1332)
    at v.createInstance (http://192.168.1.6:8443/static/out/vs/workbench/workbench.web.main.js:607:773)
    at I.createWebviewElement (http://192.168.1.6:8443/static/out/vs/workbench/workbench.web.main.js:1351:21856)
    at D.show (http://192.168.1.6:8443/static/out/vs/workbench/workbench.web.main.js:1291:41076)
    at D.claim (http://192.168.1.6:8443/static/out/vs/workbench/workbench.web.main.js:1291:39597)
    at zo.claimWebview (http://192.168.1.6:8443/static/out/vs/workbench/workbench.web.main.js:1755:82968)
    at zo.setInput (http://192.168.1.6:8443/static/out/vs/workbench/workbench.web.main.js:1755:82879)
    at async i.doSetInput (http://192.168.1.6:8443/static/out/vs/workbench/workbench.web.main.js:2656:26940)`

**Comment by zgangguoguo** [comment]
![截屏2022-05-20上午2 42 26](https://user-images.githubusercontent.com/45198849/169376445-b0a2376a-4c31-4375-b9ba-9d5b6a091f30.png)

**Comment by zgangguoguo** [comment]
I use X86_64 docker (linuxserver) same error:
![截屏2022-05-20上午3 17 14](https://user-images.githubusercontent.com/45198849/169385385-c0cd5f9c-5cc6-44b2-8806-70f1d5fcd5f6.png)

**Comment by zgangguoguo** [comment]
I use the official  release tar.gz directly in ubuntu(not docker),but same error。
![截屏2022-05-20上午9 35 00](https://user-images.githubusercontent.com/45198849/169431084-e587ddb3-20d6-429d-b037-285eb7bbeaef.png)

**Comment by cweijan** [comment]
I installed linuxserver/code-server and got the same error `Can't compute sha-256: Error: Can't compute sha-256`, this happens with any extension that uses webview, i.e. this is linuxserver /code-server bug.

**Comment by cweijan** [comment]
Try running code-server in a non-docker environment, I use this way it works fine.
https://coder.com/docs/code-server/latest/install#debian-ubuntu

**Comment by cweijan** [comment]
这个问题和这个扩展无关, 看起来是vscode的安全限制, 如果你设置了ssh端口转发到本地, 那么用localhost访问就是正常的, 如果不是localhost, 我想应该需要https才能够正常工作.
https://github.com/microsoft/vscode/blob/17c75e11805103026b943c8dc4d50a35f245f76f/src/vs/workbench/browser/webview.ts#L11
